### ISSUE TITLE
title text background?

### ISSUE THREAD

**Issue by caseyg** [freecooperunion/disorientation#38]
would love a collection of tileable or scalable backgrounds/textures to put behind the title text on each section, potentially a good place to introduce some color? or just do white text on dark background? I love the big acropolis but fear that it feels like it's floating without some kind of background. would also help separate top navigation from header from content.

**Comment by caseyg** [comment]
^ @troykreiner lemme know what you think

**Comment by troykreiner** [comment]
@caseyg  i think on the phone it looks really good, i think on the computer it does feel really big, but i kind of like it... its such an unusual way to experience an article/ title, maybe theres a reason why its uncommon...lol but idk, i like it. I guess you can try putting black background and white text, but it don't think its necessary...I don't think scale is emphasized enough on websites. I find it very refreshing but I'm also maybe in the minority group about this... I'm down to make you textures but I feel like the textures (for instance the one on CU IN COURT) seem really forced and  over designed, but if there was a more speckled, subtle texture I could get down with that.
