### ISSUE TITLE
the titles for sections are too bold 

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#40]
hey so the current titles for the sections, "lowdown" etc.

they are too bold, the counters are starting to get filled it, i think its the size and the boldness, can you use a less bold weight? i provided the different styles/weights on the dropbox, are you using the font or just image? whatever it is, can it be a slightly lighter, like instead of EXTRA BOLD, its semi bold or something. pretty sure that typeface has multiple weights.

![screen shot 2014-10-08 at 10 12 17 am](https://cloud.githubusercontent.com/assets/9045718/4563462/789adb5a-4f0e-11e4-843d-5914f175a613.png)

**Comment by caseyg** [comment]
I think this got fixed.
