### ISSUE TITLE
TWO COLUMNS?

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#47]
Can we try two columns for the opening page?

Its so long being one column, makes scrolling feel v. long

it will take advantage of the landscape proportions of the  browser a little more as well.

![screen shot 2014-10-24 at 1 23 24 pm](https://cloud.githubusercontent.com/assets/9045718/4775816/bd5d77b6-5bbb-11e4-8b4a-9ff321476490.png)

**Comment by caseyg** [comment]
Closing because this is going to end up being taken care of in #48 when chapter navigation is redesigned
