### ISSUE TITLE
3 column nav?

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#49]
I really like how you introduced the red and changed the navigation interaction.

What do you think about 3 columns?? when you go to the navigational red section?
Also could the Headlines "LOWDOWN" be larger? Will also help with the boldness vs.size issue, the counters start to get muddy when its that bold and small, pixels can't handle.

![screen shot 2014-10-25 at 2 32 26 pm](https://cloud.githubusercontent.com/assets/9045718/4781195/9f7cf0e0-5c8e-11e4-9a4e-79c15686dc34.png)
![screen shot 2014-10-25 at 2 34 22 pm](https://cloud.githubusercontent.com/assets/9045718/4781196/b2746e58-5c8e-11e4-8077-48a9a409989a.png)

**Comment by caseyg** [comment]
Sure thing. The site in its current state is basically built primarily looking at iPhones rather than larger viewports. So if your browser can show 3 cols without wrapping text you'll be served one column. It's def my intention to add back in the columns for larger viewports, but I temporarily stripped things down a bit on the code end to simplify.

think I can also fix the counters by being more specific about the font weight in the code, but will make a bit bigger too.

**Comment by troykreiner** [comment]
cool ^^^^

**Comment by caseyg** [comment]
I fucked with this today for a while and I couldn't figure out a way to do a 3 column nav with uneven widths (e.g. toolkit titles are SO short, and background titles are SO long) that is also fluid with varying browser widths that doesn't look shitty. 

Ok to leave it as a centered column for now? 

p.s. I made some other nav improvements, like having it say "Table of Contents" on hover.

**Comment by troykreiner** [comment]
Alrighty, lets give this another shot. If it still dont work lets just drop the columns.

I took a stab at the layout for the columns. I shorted COOPER UNION to C.U. for two titles because they were too long

without type styles but just paragraph styles

![screen shot 2015-04-21 at 11 10 09 am](https://cloud.githubusercontent.com/assets/9045718/7259283/1f8aa070-e817-11e4-9ce6-eaf482895920.png)

**Comment by troykreiner** [comment]
dont mind that extra gab between tool kit and lowdown. threw it together fast

**Comment by caseyg** [comment]
![nav](https://cloud.githubusercontent.com/assets/462020/7373265/63c4cef0-ed99-11e4-9e2e-abf8a4a4e328.gif)
