### ISSUE TITLE
3 lines for the navigation symbol/icon?

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#50]
could the icon for the navigation symbol be 3 lines? the two seems harder to understand, 3 lines seems more legible @caseyg 
![screen shot 2014-10-29 at 9 48 00 am](https://cloud.githubusercontent.com/assets/9045718/4830144/8d11217e-5f8b-11e4-863c-08e8f8a9a555.png)

**Comment by caseyg** [comment]
weird it's three lines for me on mac chrome Version 38.0.2125.111, can you tell me the url of the page where you see this, if it's a specific one, and also which browser you're using?

![screen shot 2014-10-29 at 2 59 55 pm](https://cloud.githubusercontent.com/assets/462020/4832627/d584d2cc-5f9d-11e4-8bce-43ccf3b068d4.png)

**Comment by troykreiner** [comment]
i see at 3 lines now! :)
