### ISSUE TITLE
a note on abridgement

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#52]
this copy seems like it could be updated since its already online, was probably C&P from the printed version

 @caseyg 
![screen shot 2014-10-29 at 9 52 16 am](https://cloud.githubusercontent.com/assets/9045718/4830190/ff35e8de-5f8b-11e4-8023-51de2aad8788.png)

**Comment by troykreiner** [comment]
Ps Casey would love to catch up with you on this took about any updates or long term disorientation site your thoughts about engagement

**Comment by troykreiner** [comment]
*talk about

**Comment by caseyg** [comment]
Yessss @troykreiner I will upload screenshots to the issues, cuz like I Am Not A Designer so I need heeelp, but I can at least get starts at ideas about how to make things slightly better. Down to bounce back and forth in parallel with improving the content until things are actually awesome and exist this time around.
