### ISSUE TITLE
Remove this rule below colophon

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#60]
![screen shot 2015-04-21 at 10 19 00 am](https://cloud.githubusercontent.com/assets/9045718/7258216/df31c19a-e80f-11e4-8af3-55591d118fd8.png)

This rule i think is overkill but the other ones are working well!

**Comment by caseyg** [comment]
What about removing the colophon section from the web? Sort of serves no purpose.

**Comment by caseyg** [comment]
Or making it the last section, moving it around now. Let me know what you think

**Comment by caseyg** [comment]
@troykreiner do you still want any rules removed with the new section order?

**Comment by troykreiner** [comment]
My thoughts on the Colophon are the following:
1. Get rid of it entirely.
2. Refine it and actually make it a Colophon and add credit,
   Website is Powered by: (Wordpress) whatever show off some of the shit you are working with
   Fonts used: Acropolis (foundry)etc.
   Special Thanks: whoever or nothing

**Comment by caseyg** [comment]
![screen shot 2015-04-21 at 1 43 08 pm](https://cloud.githubusercontent.com/assets/462020/7258724/5d583984-e82c-11e4-8eea-70dfe8d8f290.png)

**Comment by troykreiner** [comment]
Cool couple notes:

Can you move the Web, Print and Type below the "no stupid questions"

Can we remove the underline from this section? Just starting to feeeel super heavy blue link underlineeeess

**Comment by caseyg** [comment]
![screen shot 2015-04-21 at 1 55 05 pm](https://cloud.githubusercontent.com/assets/462020/7258973/08c6fde0-e82e-11e4-94e9-4d7c49c52ca5.png)

**Comment by troykreiner** [comment]
perfecto
