### ISSUE TITLE
Bold Headers TOO Bold

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#61]
![screen shot 2015-04-21 at 10 19 54 am](https://cloud.githubusercontent.com/assets/9045718/7258238/00a2fb64-e810-11e4-8af2-ecb9c181b078.png)

I remember bringing up this issue earlier on, can we use a slightly less bolder version, I feel like at that size the counters start to fill-in too much. 

-TK

**Comment by caseyg** [comment]
![screen shot 2015-04-21 at 1 33 21 pm](https://cloud.githubusercontent.com/assets/462020/7258493/ff3892be-e82a-11e4-9cd2-a19ff3bb87fd.png)
