### ISSUE TITLE
Adding an additional hover state to the PDF download

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#62]
![screen shot 2015-04-21 at 10 22 31 am](https://cloud.githubusercontent.com/assets/9045718/7258278/5589bc44-e810-11e4-8862-7e100d79e737.png)

I think this section is looking super tight.

I feel like it might be helpful to add some hover-state text that just indicates the title, or edition like DISO READER EDITION 1, maybe its over kill but just to reaffirm what it is you will be downloading?

**Comment by caseyg** [comment]
![screen shot 2015-04-21 at 1 30 37 pm](https://cloud.githubusercontent.com/assets/462020/7258452/a3ed684e-e82a-11e4-90ef-59c229c7e72f.png)

**Comment by troykreiner** [comment]
Yeah that seems more clear
