### ISSUE TITLE
Ragging late night skype date

### ISSUE THREAD

**Issue by troykreiner** [freecooperunion/disorientation#64]
Also not critical but lets have a quick skype meeting about some funky ragging stuff just on the landing page, there are bunch of widows I think we could easily avoid. Since the web browser size is not effecting the body copy width, it seems like its scaling.

![screen shot 2015-04-21 at 10 25 43 am](https://cloud.githubusercontent.com/assets/9045718/7258366/e61efff8-e810-11e4-8bf0-ff069065e63f.png)
![screen shot 2015-04-21 at 10 25 35 am](https://cloud.githubusercontent.com/assets/9045718/7258365/e61eca38-e810-11e4-991b-d0683731c88e.png)
![screen shot 2015-04-21 at 10 25 45 am](https://cloud.githubusercontent.com/assets/9045718/7258364/e61b7540-e810-11e4-8aad-63e11a38dd8e.png)

**Comment by caseyg** [comment]
LOL. I am pretty sure there is a jquery plugin that I could drop in that will take care to not let any word end of its own line. Lemme plop that in before, and then anything that's still a mess I can add `&nbsp;` characters instead of regular spaces between to ensure it sticks together.

**Comment by troykreiner** [comment]
ohh whoops yeah I should know that...

good call

but we can still have a skype date

**Comment by caseyg** [comment]
YESS!! :ring:

**Comment by caseyg** [comment]
Applying http://matthewlein.com/widowfix/

**Comment by caseyg** [comment]
![screen shot 2015-04-21 at 1 59 28 pm](https://cloud.githubusercontent.com/assets/462020/7259059/a9d48f4a-e82e-11e4-8b9c-ecb33f81d566.png)

![screen shot 2015-04-21 at 1 59 31 pm](https://cloud.githubusercontent.com/assets/462020/7259063/ac623d84-e82e-11e4-8ff9-c534892428fc.png)

![screen shot 2015-04-21 at 1 59 37 pm](https://cloud.githubusercontent.com/assets/462020/7259067/b0e53d5c-e82e-11e4-974b-b6c3e0700c5a.png)

**Comment by troykreiner** [comment]
Fabuloso
